### ISSUE TITLE
Malware labeled via Cynet

### ISSUE THREAD

**Issue by bionictoothpick** [GibzFGC/FoxxiBot#21]
The program autoruns, and isn't allowing it to be deleted.

**Comment by GibzFGC** [comment]
The application has no way of auto-running, you have to run it yourself via the console application EXE on Windows or via command shell on Linux.

It's also only a Twitch / Discord bot built in C#, all code is given and can be checked.

**Comment by bionictoothpick** [comment]
I downloaded, unzipped and ran the foxxibot.exe.

It is running after reboot.

Original filename listed as FoxxiBot.dll

I was able to delete all other files in the unzipped directory, but not the .exe.

**Comment by GibzFGC** [comment]
It's impossible for it to be running after a reboot as long as you haven't tried running it again or added it as a start-up application. The EXE can't function without any of it's files so it'd close and error anyway

**Comment by bionictoothpick** [comment]
[https://ibb.co/jGt9cpK](url)

Task manager can't find it to kill it either.

**Comment by GibzFGC** [comment]
I have no idea what in System could be using it, so this is very strange. Talk on Discord, it's easier if possible

**Comment by abitofBaileys** [comment]
Get [Microsoft's File Locksmith](https://learn.microsoft.com/en-us/windows/powertoys/file-locksmith) and in your explorer, right click on the .exe and then "What's using this file?" to see which process uses it and let us know.

**Comment by bionictoothpick** [comment]
Thanks for helping me further investigate. It appears everything has returned to normal after removing permissions from the file, rebooting, and then removing from the command line. No further action is needed at this time.
